trigger:
- master

pool: 'WindowsPool'

variables:
  solution: '**/*.csproj'
  runtime: 'win-x64'
  configuration: 'Release'
  
steps:
- task: replacetokens@5
  inputs:
    targetFiles: '**/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    actionOnNoFiles: 'fail'
  
- task: UseDotNet@2
  displayName: 'Use .Net Core SDK 6.0'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build DTPIT App'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(configuration) -r $(runtime)'

- task: DotNetCoreCLI@2
  displayName: 'Take release for Windows x64'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '-c $(configuration) -r $(runtime) -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Ariza-Bildiri-App'
    publishLocation: 'Container'
